import Navbar from '@/components/Navbar2'
import '@/app/globals.css'
import type { Metadata } from 'next'
import { Open_Sans, Lato } from 'next/font/google'
import Footer from '@/components/Footer2'

const opensans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-opensans',
})


const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  variable: '--font-lato',
  style: ['normal', 'italic']
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${opensans.variable} ${lato.variable}  bg-green-50 text-gray-900`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
